### ISSUE TITLE
meets Tokio `enble_io()` error

### ISSUE THREAD

**Issue by violin0622** [tokio-rs/turmoil#126]
I was trying to init a simulator  runs a closure which bind to localhost. like this:

```rust
#[test]
fn test_main() -> Result {
    let mut sim = Builder::new()
        .build();

    sim.client("10.129.11.11", async {
        let (mut sock, addr) = TcpListener::bind((IpAddr::from(Ipv6Addr::UNSPECIFIED), 8080))
            .await?
            .accept()
            .await?;
        sock.write_i32(124).await?;
        Ok(())
    });
    sim.run()
}
```

And I meets error :
![截屏2023-06-30 19 35 36](https://github.com/tokio-rs/turmoil/assets/6880156/2ccc9945-6018-46c1-8ea5-4238149552d8)

It seems turmoil didn't call tokio's `enable_io()` method when initiating a tokio runtime? 
related code in turmoil/src/rt.rs

```rust
fn init() -> (Runtime, LocalSet) {
    let mut builder = tokio::runtime::Builder::new_current_thread();

    #[cfg(tokio_unstable)]
    builder.unhandled_panic(tokio::runtime::UnhandledPanic::ShutdownRuntime);

    let tokio = builder.enable_time().start_paused(true).build().unwrap();

    tokio.block_on(async {
        // Sleep to "round" `Instant::now()` to the closest `ms`
        tokio::time::sleep(Duration::from_millis(1)).await;
    });

    (tokio, new_local())
}
```

**Comment by camshaft** [comment]
That `TcpListener` needs to be [the turmoil version](https://docs.rs/turmoil/latest/turmoil/net/struct.TcpListener.html), not tokio's. Note that `enable_io` shouldn't be called, since all IO is simulated through turmoil and no actual OS sockets are used. The error message could be a better, though.

**Comment by mcches** [comment]
> The error message could be a better, though.

Any ideas on how we can improve this? That is a `tokio` panic, so without a tighter integration I'm not sure how to intercept that in a reasonable way.

**Comment by camshaft** [comment]
Yeah I think tighter integration is probably the only option here, unfortunately.

**Comment by violin0622** [comment]
> That `TcpListener` needs to be [the turmoil version](https://docs.rs/turmoil/latest/turmoil/net/struct.TcpListener.html), not tokio's. Note that `enable_io` shouldn't be called, since all IO is simulated through turmoil and no actual OS sockets are used. The error message could be a better, though.

Yes, that was my fault. Thanks for your help!
