### ISSUE TITLE
Error `ConnectionRefused` when binding UdpSocket to `localhost`

### ISSUE THREAD

**Issue by merklefruit** [tokio-rs/turmoil#136]
[This line in the `UdpSocket` implementation](https://github.com/tokio-rs/turmoil/blob/4c23b669e1499b2a1a57842dc60b6829cc887253/src/net/udp.rs#L104C68-L104C68) suggests that it can be used with `localhost`, `::` or `0.0.0.0`.

But if we try to change the binding address from "unspecified" to "localhost" in the udp tests, they all fail with `ConnectionRefused` error.

If this is the expected behaviour for the socket, that part of documentation can be seen as somewhat misleading.

**Comment by mcches** [comment]
Which line in the udp tests are you referring to? The majority of those tests are between 2 hosts, which should error if the socket is bound on localhost.

**Comment by merklefruit** [comment]
> The majority of those tests are between 2 hosts, which should error if the socket is bound on localhost.

I see now where I misunderstood. I thought hosts shared the same network interface and could communicate over localhost.
I appreciate the clarification. Thanks for helping clear things up and for the quick response!
