### ISSUE TITLE
Update gRPC example to latest hyper, tonic and tower

### ISSUE THREAD

**Issue by LeonHartley** [tokio-rs/turmoil#180]
The examples still reference older versions of hyper, tonic and tower. These libraries have moved on quite a bit so it would be nice to see them being refreshed using the latest versions of the APIs.

**Comment by mcches** [comment]
Would you be interested in picking up this task?

**Comment by LeonHartley** [comment]
Yeah I can sort it. I've just recently upgraded hyper, tonic and tower in a project that we use Turmoil for testing too

**Comment by mcches** [comment]
Much appreciated! I can PR as soon as you get something up.

**Comment by LeonHartley** [comment]
Raised the PR for that
