### ISSUE TITLE
Time and clocks

### ISSUE THREAD

**Issue by marcbowes** [tokio-rs/turmoil#21]
https://github.com/tokio-rs/turmoil/blob/main/src/host.rs#L69

I think code like this should be replaced with something that sources time off a virtual clock. If so, there are two broad patterns to apply:

1. Pass the instant 'now' in as a param
2. Given the host a timesource and fetch 'now' from said source

**Comment by marcbowes** [comment]
I'm struggling to understand how things work right now.

1. When the sim runs, it ticks 1ms forward https://github.com/tokio-rs/turmoil/blob/2dd03ada8eaddd8ca036e663606d9efd1dd156bd/src/sim.rs#L152-L161
2. When a message is received, it is only delivered based on whether wallclock now has advanced.

.. presumably this means that for fast tests (i.e. ticks are < 1ms) the code lands up waiting for realtime to advance?

on the recv path (https://github.com/tokio-rs/turmoil/blob/main/src/io.rs#L20) it looks like we will wait for a notification, which (I think) is triggered when the host ticks past the wallclock-now of the message delivery time (which is based on fake time on the send host - which also seems busted to me)

**Comment by marcbowes** [comment]
> which is based on fake time on the send host - which also seems busted to me

I take that back. `Host::send` is actually called on the receiving host. So the method name is just confusing.

**Comment by marcbowes** [comment]
There is some magic (through globals, my favorite) going on that makes this more or less work out the way it should. I'm not sure it's 100% yet, so I plan on digging more before closing this out. Hopefully I can add some comments to help explain how it all works.

**Comment by carllerche** [comment]
You can schedule some time with me and I can walk you through it. Short version is that it uses Tokio’s Instant::now which can be made virtual.

**Comment by marcbowes** [comment]
See #23
