### ISSUE TITLE
Add support for `TcpStream#peek`

### ISSUE THREAD

**Issue by battesonb** [tokio-rs/turmoil#55]
Method: [TcpStream#peek](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.peek)

I have run into an issue that requires the use of this method. I would be happy to get started on a fix, but I'm uncertain on the approach to take. The issue I'm running across is (1) that `self` is immutably referenced:

```rust
pub async fn peek(&self, buf: &mut [u8]) -> io::Result<usize>
```

This was previously [mutable and relied on `poll_peek`](https://github.com/tokio-rs/tokio/pull/2151).

The other issue (2) is that turmoil currently implements the `ReadHalf` and `WriteHalf` using a `tokio::mpsc` channel. However, it doesn't look like the `Receiver` has an option to immutably read the internal lock-free list.

So my question is whether we should paper over the `ReadHalf` with an internal data structure, try to get this implemented in tokio/chan or some other potential solution I'm missing?

**Comment by mcches** [comment]
I used interior mutability with a simplified queue/Notify channel for the listener: https://github.com/tokio-rs/turmoil/blob/main/src/net/tcp/listener.rs#L50

Something like this would probably be lowest friction.

**Comment by mcches** [comment]
I'm closing this as #64 is handling it, and this issue was used to asked questions about how to implement it.
