### ISSUE TITLE
Support loopback

### ISSUE THREAD

**Issue by mcches** [tokio-rs/turmoil#79]
Hosts currently may only bind to `0.0.0.0`.

https://github.com/tokio-rs/turmoil/blob/main/src/net/tcp/listener.rs#L28

Add support to bind `127.0.0.1` to unblock loopback scenarios. We need to decide how network topology is affected by these changes. For example, it doesn't make sense to allow partitions within a host.

**Comment by th7nder** [comment]
Hey! I'd love to pick this one up as my first issue.

Let's clarify, what are the loopback scenarios you mentioned?

**Comment by mcches** [comment]
Allow hosts to bind to localhost (e.g. 127.0.0.1) socket addresses, which are only reachable from within said host.

**Comment by th7nder** [comment]
```
#[test]
fn connects_within_a_host() -> Result {

    let mut sim = Builder::new().build();

    sim.host("server", || async {
        let listener = TcpListener::bind((IpAddr::from(Ipv4Addr::LOCALHOST), PORT)).await?;

        let _ = listener.accept().await;
        tokio::spawn(async move {
            loop {
                if let Ok((mut stream, _socket)) = listener.accept().await {
                    let _ = stream.write_u8(7).await;
                }
            }
        });

        let mut stream = TcpStream::connect(("server", PORT))
            .await
            .expect("should have connected");

        assert_eq!(7, stream.read_u8().await.expect("successful read"));

        Ok(())
    });

    sim.client("client", async {
        assert_error_kind(
            TcpStream::connect(("server", PORT)).await,
            io::ErrorKind::ConnectionRefused,
        );
        Ok(())
    });
}
```
Questions:
1. Am I going into the right direction?
2. Should we consider being able to use `127.0.0.1` or `localhost` inside of a host as a reference to itself? I noticed that DNS uses 127.0.x.y addresses internally.

**Comment by mcches** [comment]
> Am I going into the right direction?

Yes! I am curious why you need the first accept that ignores the result?

```rust
let _ = listener.accept().await;
```

> Should we consider being able to use 127.0.0.1 or localhost inside of a host as a reference to itself? I noticed that DNS uses 127.0.x.y addresses internally.

I think that makes a lot of sense. We should probably reserve that IP adds and also make sure `"localhost"` resolves to it in DNS.

So when you connect from within a host you can just do:

```rust
let mut stream = TcpStream::connect(("localhost", PORT)).await?;
```

**Comment by th7nder** [comment]
The first accept was an artifact of some previous experimentation, good catch!

This makes sense:
```rust
let mut stream = TcpStream::connect(("localhost", PORT)).await?;
```
But does this actually makes sense?
```rust
let mut stream = TcpStream::connect(("server", PORT)).await?;
```
If we bound to something to `localhost:1234`, should it be also reachable from `server:1234` even from *within* the host? 
I don't think it should.

**Comment by mcches** [comment]
I agree. The second one shouldn't work.

**Comment by mh32** [comment]
I've added https://github.com/tokio-rs/turmoil/pull/118 which adds simply support for loopback by having hosts directly send loopback traffic to themselves rather than route through the topology. While this is somewhat similar to how real hosts work, a side effect of my change is that network control APIs like `hold` and `release` do not work on loopback.

Routing through topology turned out to be fairly tricky due to how hosts are identified by ip address. I think where we want to get long term is to identify each host by something else (Mac address?) and allow multiple interfaces per host. This would allow us to change https://github.com/tokio-rs/turmoil/pull/113 to support hosts with both ipv4 and ipv6 addresses.
